import IsoDomPurify from 'isomorphic-dompurify';

export function domPurify(dirty: string | Node, cfg?: IsoDomPurify.Config) {
  return IsoDomPurify.sanitize(dirty, {
    ALLOWED_TAGS: [
      'a',
      'p',
      'br',
      'strong',
      'em',
      'b',
      'i',
      'u',
      's',
      'blockquote',
      'pre',
      'code',
      'ul',
      'ol',
      'li',
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'hr',
      'table',
      'thead',
      'tbody',
      'tr',
      'td',
      'th',
      'span',
      'img',
    ],
    ALLOWED_ATTR: [
      'href',
      'target',
      'rel',
      'src',
      'alt',
      'title',
      'width',
      'height',
      'colspan',
      'rowspan',
      'class',
    ],
    FORBID_TAGS: [
      'script',
      'iframe',
      'style',
      'meta',
      'link',
      'object',
      'embed',
      'base',
      'form',
    ],
    ...cfg,
  });
}
