services:
  - type: web
    name: nearn-app
    runtime: node
    region: frankfurt
    plan: standard
    buildCommand: pnpm install && pnpm prisma generate && pnpm build
    preDeployCommand: pnpm prisma migrate deploy
    repo: https://github.com/NEAR-DevHub/nearn
    branch: prod
    domains:
      - nearn.io
    startCommand: pnpm start
    envVars:
      - key: CRON_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_URL
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: NODE_VERSION
        value: 20.11.0
      - key: ZEROBOUNCE_API_KEY
        sync: false
      - key: EMAIL_SERVER_USER
        value: resend
      - key: EMAIL_SERVER_HOST
        value: smtp.resend.com
      - key: EMAIL_SERVER_PORT
        value: 465
      - key: AIRTABLE_GRANTS_API_TOKEN
        sync: false
      - key: AIRTABLE_GRANTS_BASE_ID
        sync: false
      - key: AIRTABLE_GRANTS_TABLE_NAME
        sync: false
      - key: AIRTABLE_GRANTS_REGIONS_TABLE_NAME
        sync: false
      - key: AIRTABLE_RECIPIENTS_TABLE
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EARNCOGNITO_URL
        sync: false
      - key: EARNCOGNITO_SECRET
        sync: false
      - key: GOOGLE_ID
        sync: false
      - key: GOOGLE_SECRET
        sync: false
      - key: EMAIL_BACKEND
        sync: false
      - key: NEXT_PUBLIC_POSTHOG_HOST
        sync: false
      - key: NEXT_PUBLIC_POSTHOG_KEY
        sync: false
      - key: REPLY_TO_EMAIL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: UNSUB_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CEO_EMAIL
        sync: false
    autoDeploy: true
  - type: web
    name: nearn-app-staging
    repo: https://github.com/NEAR-DevHub/nearn
    branch: staging
    runtime: node
    region: frankfurt
    plan: standard
    previews:
      generation: manual
      plan: starter
    buildCommand: pnpm install && pnpm prisma generate && pnpm build
    preDeployCommand: pnpm prisma migrate deploy
    startCommand: pnpm start
    envVars:
      - key: CRON_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_URL
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: NODE_VERSION
        value: 20.11.0
      - key: ZEROBOUNCE_API_KEY
        sync: false
      - key: EMAIL_SERVER_USER
        value: resend
      - key: EMAIL_SERVER_HOST
        value: smtp.resend.com
      - key: EMAIL_SERVER_PORT
        value: 465
      - key: AIRTABLE_GRANTS_API_TOKEN
        sync: false
      - key: AIRTABLE_GRANTS_BASE_ID
        sync: false
      - key: AIRTABLE_GRANTS_TABLE_NAME
        sync: false
      - key: AIRTABLE_GRANTS_REGIONS_TABLE_NAME
        sync: false
      - key: AIRTABLE_RECIPIENTS_TABLE
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EARNCOGNITO_URL
        sync: false
      - key: EARNCOGNITO_SECRET
        sync: false
      - key: GOOGLE_ID
        sync: false
      - key: GOOGLE_SECRET
        sync: false
      - key: EMAIL_BACKEND
        sync: false
      - key: NEXT_PUBLIC_POSTHOG_HOST
        sync: false
      - key: NEXT_PUBLIC_POSTHOG_KEY
        sync: false
      - key: REPLY_TO_EMAIL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: UNSUB_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CEO_EMAIL
        sync: false
    autoDeploy: true
  - type: web
    region: frankfurt
    plan: standard
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest
    disk: # Persistent disk configuration
      name: n8n-disk
      mountPath: /home/node
      sizeGB: 5 # optional
    envVars:
      # Generates a base64-encoded key for
      # encrypting credentials in n8n
      #
      # Do not modify this value after it's generated!
      # If you do, you'll lose access to all credentials
      # encrypted with the previous value.
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_RUNNERS_ENABLED
        value: true
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: true
      - key: PORT
        value: 5678
      - key: STAGING_SECRET
        fromService:
          name: nearn-app-staging
          type: web
          envVarKey: CRON_SECRET
      - key: PROD_SECRET
        fromService:
          name: nearn-app
          type: web
          envVarKey: CRON_SECRET
      - key: TELEGRAM_TOKEN
        sync: false
