export interface FiatCurrency {
  code: string;
  name: string;
}

export const fiatCurrencies: FiatCurrency[] = [
  { code: 'USD', name: 'US Dollar' },
  { code: 'EUR', name: 'Euro' },
  { code: 'ALL', name: 'Albanian lek' },
  { code: 'DZD', name: 'Algerian dinar' },
  { code: 'AOA', name: 'Angolan kwanza' },
  { code: 'ARS', name: 'Argentine peso' },
  { code: 'AUD', name: 'Australian dollar' },
  { code: 'AWG', name: 'Aruban florin' },
  { code: 'AZN', name: 'Azerbaijani manat' },
  { code: 'BBD', name: 'Barbadian dollar' },
  { code: 'BMD', name: 'Bermudian dollar' },
  { code: 'BHD', name: 'Bahraini dinar' },
  { code: 'BDT', name: 'Bangladeshi taka' },
  { code: 'BZD', name: 'Belize dollar' },
  { code: 'BOB', name: 'Boliviano' },
  { code: 'BAM', name: 'Convertible mark' },
  { code: 'BRL', name: 'Brazilian real' },
  { code: 'BND', name: 'Brunei dollar' },
  { code: 'BGN', name: 'Bulgarian lev' },
  { code: 'BTN', name: 'Bhutanese ngultrum' },
  { code: 'BIF', name: 'Burundian franc' },
  { code: 'MMK', name: 'Myanmar kyat' },
  { code: 'BWP', name: 'Botswana pula' },
  { code: 'KHR', name: 'Cambodian riel' },
  { code: 'CVE', name: 'Cape Verdean escudo' },
  { code: 'KYD', name: 'Cayman Islands dollar' },
  { code: 'CLP', name: 'Chilean peso' },
  { code: 'COP', name: 'Colombian peso' },
  { code: 'KMF', name: 'Comorian franc' },
  { code: 'CUP', name: 'Cuban peso' },
  { code: 'CAD', name: 'Canadian dollar' },
  { code: 'CHF', name: 'Swiss franc' },
  { code: 'CNY', name: 'Chinese yuan' },
  { code: 'CZK', name: 'Czech koruna' },
  { code: 'DJF', name: 'Djiboutian franc' },
  { code: 'DOP', name: 'Dominican peso' },
  { code: 'DKK', name: 'Danish krone' },
  { code: 'ERN', name: 'Eritrean nakfa' },
  { code: 'EGP', name: 'Egyptian pound' },
  { code: 'ETB', name: 'Ethiopian birr' },
  { code: 'FJD', name: 'Fijian dollar' },
  { code: 'FKP', name: 'Falkland Islands pound' },
  { code: 'GEL', name: 'Georgian lari' },
  { code: 'GIP', name: 'Gibraltar pound' },
  { code: 'GTQ', name: 'Guatemalan quetzal' },
  { code: 'GBP', name: 'British pound sterling' },
  { code: 'GHS', name: 'Ghanaian cedi' },
  { code: 'GMD', name: 'Gambian dalasi' },
  { code: 'GNF', name: 'Guinean franc' },
  { code: 'HKD', name: 'Hong Kong dollar' },
  { code: 'HUF', name: 'Hungarian forint' },
  { code: 'HNL', name: 'Honduran lempira' },
  { code: 'IDR', name: 'Indonesian rupiah' },
  { code: 'INR', name: 'Indian rupee' },
  { code: 'ISK', name: 'Icelandic króna' },
  { code: 'ILS', name: 'Israeli new shekel' },
  { code: 'JPY', name: 'Japanese yen' },
  { code: 'JMD', name: 'Jamaican dollar' },
  { code: 'JOD', name: 'Jordanian dinar' },
  { code: 'KZT', name: 'Kazakhstani tenge' },
  { code: 'KWD', name: 'Kuwaiti dinar' },
  { code: 'KGS', name: 'Kyrgyzstani som' },
  { code: 'KRW', name: 'South Korean won' },
  { code: 'KES', name: 'Kenyan shilling' },
  { code: 'LRD', name: 'Liberian dollar' },
  { code: 'MAD', name: 'Moroccan dirham' },
  { code: 'MGA', name: 'Malagasy ariary' },
  { code: 'MWK', name: 'Malawian kwacha' },
  { code: 'MYR', name: 'Malaysian ringgit' },
  { code: 'MKD', name: 'Macedonian denar' },
  { code: 'MVR', name: 'Maldivian rufiyaa' },
  { code: 'MXN', name: 'Mexican peso' },
  { code: 'MDL', name: 'Moldovan leu' },
  { code: 'MOP', name: 'Macanese pataca' },
  { code: 'NAD', name: 'Namibian dollar' },
  { code: 'NPR', name: 'Nepalese rupee' },
  { code: 'NIO', name: 'Nicaraguan córdoba' },
  { code: 'NZD', name: 'New Zealand dollar' },
  { code: 'NGN', name: 'Nigerian naira' },
  { code: 'NOK', name: 'Norwegian krone' },
  { code: 'PHP', name: 'Philippine peso' },
  { code: 'PLN', name: 'Polish złoty' },
  { code: 'RON', name: 'Romanian leu' },
  { code: 'RWF', name: 'Rwandan franc' },
  { code: 'SEK', name: 'Swedish krona' },
  { code: 'SGD', name: 'Singapore dollar' },
  { code: 'SSP', name: 'South Sudanese pound' },
  { code: 'SAR', name: 'Saudi riyal' },
  { code: 'TZS', name: 'Tanzanian shilling' },
  { code: 'UAH', name: 'Ukrainian hryvnia' },
  { code: 'XAF', name: 'Central African CFA franc' },
  { code: 'XOF', name: 'West African CFA franc' },
  { code: 'ZAR', name: 'South African rand' },
  { code: 'ZMW', name: 'Zambian kwacha' },
  { code: 'ZWL', name: 'Zimbabwean dollar' },
];
